version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
      - match:
          dependency_type: "all"
          update_type: "all"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "security"
      - match:
          dependency_type: "direct"
          update_type: "all"
