name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_ENV: "ci"

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest]

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: casbin_objection_adapter_test_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: casbin_objection_adapter_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: volta install pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test:coverage
      - run: pnpm run build
